version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: gokulkrishnan
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app1:
    build: .
    # container_name: my_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

  app2:
    build: .
    # container_name: my_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8081:8080"

  app3:
    build: .
    # container_name: my_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8082:8080"


  

volumes:
  postgres_data:
